In [1]:
# .read_csv()

In [2]:
import numpy as np
import pandas as pd

In [3]:
path = '../../../_data_py_for_da/'

In [4]:
df = pd.read_csv(path+'examples/ex1.csv')

df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [5]:
pd.read_csv(path+'examples/ex2.csv')

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [6]:
pd.read_csv(path+'examples/ex2.csv', 
            header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [7]:
pd.read_csv(path+'examples/ex2.csv', 
            names=['a', 'b', 'c', 'd', 'message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [8]:
names = ['a', 'b', 'c', 'd', 'message']

pd.read_csv(path+'examples/ex2.csv',
            names=names,
            index_col='message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [9]:
parsed = pd.read_csv(path+'examples/csv_mindex.csv')

parsed

  key1 key2  value1  value2
0  one    a       1       2
1  one    b       3       4
2  one    c       5       6
3  one    d       7       8
4  two    a       9      10
5  two    b      11      12
6  two    c      13      14
7  two    d      15      16

In [10]:
parsed = pd.read_csv(path+'examples/csv_mindex.csv',
                     index_col=['key1', 'key2'])

parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [11]:
result = pd.read_csv(path+'examples/ex3.txt',
                     sep=r'\s+')

result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [12]:
pd.read_csv(path+'examples/ex4.csv')

                                                                      # hey!
a                                                  b        c   d    message
# just wanted to make things more difficult for... nan      nan nan      NaN
# who reads CSV files with computers                anyway? nan nan      NaN
1                                                  2        3   4      hello
5                                                  6        7   8      world
9                                                  10       11  12       foo

In [13]:
pd.read_csv(path+'examples/ex4.csv',
            skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [14]:
result = pd.read_csv(path+'examples/ex5.csv')

result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [15]:
pd.isna(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [16]:
result = pd.read_csv(path+'examples/ex5.csv',
                     na_values=['foo'])

result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [17]:
result2 = pd.read_csv(path+'examples/ex5.csv', 
                      keep_default_na=False)

result2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [18]:
result2.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [19]:
result3 = pd.read_csv(path+'examples/ex5.csv',
                      keep_default_na=False,
                      na_values=['NA'])

result3

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [20]:
result3.isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [21]:
sentinels = {'message': ['foo', 'NA'], 
             'something': ['two']}

pd.read_csv(path+'examples/ex5.csv',
            na_values=sentinels,
            keep_default_na=False)

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       NaN  5   6       8   world
2     three  9  10  11  12     NaN