In [1]:
# .to_csv()

In [2]:
import numpy as np
import pandas as pd

import sys

In [3]:
path = '../../../_data_py_for_da/'

In [4]:
data = pd.read_csv(path+'examples/ex5.csv')

data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [5]:
data.to_csv('out.csv')

pd.read_csv('out.csv')

   Unnamed: 0 something  a   b     c   d message
0           0       one  1   2   3.0   4     NaN
1           1       two  5   6   NaN   8   world
2           2     three  9  10  11.0  12     foo

In [6]:
data.to_csv(sys.stdout, 
            sep='|')

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [7]:
data.to_csv(sys.stdout, 
            na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [8]:
data.to_csv(sys.stdout, 
            index=False,
            header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [9]:
data.to_csv(sys.stdout,
            index=False,
            columns=['a', 'b', 'c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [10]:
data.to_csv('out.csv',
            index=False)

pd.read_csv('out.csv')

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [11]:
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo