In [1]:
# json.loads() and json.dumps()

In [2]:
import numpy as np
import pandas as pd

import json
import sys

In [3]:
path = '../../../_data_py_for_da/'

In [4]:
obj = '''
{
    "name": "Wes",
    "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
    "pet": null,
    "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
                 {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
'''

In [5]:
result = json.loads(obj)
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

In [6]:
asjson = json.dumps(result)
asjson

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

In [7]:
# to DataFrame

In [8]:
siblings = pd.DataFrame(result['siblings'],
                        columns=['name', 'age'])
siblings

    name  age
0  Scott   34
1  Katie   42

In [9]:
# pandas.read_json

In [10]:
with open(path+'examples/example.json') as f:
    print(f.read())

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [11]:
data = pd.read_json(path+'examples/example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [12]:
# pandas.to_json

In [13]:
data.to_json(sys.stdout)

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [14]:
data.to_json(sys.stdout, orient='records')

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]