In [1]:
# indexing

In [2]:
import numpy as np
import pandas as pd

In [3]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [4]:
# for Series

# AVOID BARE ELEMENT LOOKUP 
# ser[label]
#
# USE BARE ONLY FOR BOOLEAN MASK
# ser[mask]
#
# USE 
# ser.loc[label] (inclusive if slice) AND 
# ser.iloc[ind] (exclusive if slice)

In [5]:
obj['b']

np.float64(1.0)

In [6]:
obj.loc['b']

np.float64(1.0)

In [7]:
obj.iloc[1]

np.float64(1.0)

In [8]:
obj.iloc[2:4]

c    2.0
d    3.0
dtype: float64

In [9]:
obj.loc[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [10]:
obj.iloc[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [11]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [12]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [13]:
obj.loc['b':'c']

b    1.0
c    2.0
dtype: float64

In [14]:
obj.loc['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [15]:
# for DataFrame

# BARE 
# frame[col_name]
# frame[mask]
#
# ONE ARGUMENT for .loc / .iloc
# frame.loc[row_name] / .iloc[row_ind]
# frame.loc[row_slice] / .iloc[row_slice]
#
# TWO ARGUMENTS for .loc / .iloc
# frame.loc[row_label, column_label]
# frame.iloc[row_ind, column_ind]

In [16]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [17]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [18]:
data.loc[:, 'two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [19]:
data[['three', 'one']]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [20]:
data.loc[:, ['three', 'one']]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [21]:
# special cases

In [22]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [23]:
data.iloc[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [24]:
data.iloc[:2, :]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [25]:
data[data['three'] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [26]:
data.loc[data.loc[:, 'three'] > 5, :]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [27]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [28]:
data[data < 5] = 0
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [29]:
# selection on DataFrame with .loc and .iloc

In [30]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [31]:
data.loc['Colorado']

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [32]:
data.loc[['Colorado', 'New York']]

          one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [33]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [34]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [35]:
data.iloc[[2, 1]]

          one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [36]:
data.iloc[2, [3, 0 , 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [37]:
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    0    5
Utah        11    8    9

In [38]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [39]:
data.iloc[:, :3][data.three > 5]

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [40]:
data.loc[data['three'] > 5].iloc[:, :3]

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [41]:
data.iloc[:, :3].loc[data['three'] > 5]

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [42]:
data.loc[data.three >= 2]

          one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [43]:
# integer indexing pitfalls

In [44]:
ser = pd.Series(np.arange(3.0))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [45]:
ser[-1]

KeyError: -1

In [46]:
ser.iloc[-1]

np.float64(2.0)

In [47]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [48]:
ser.iloc[:2]

0    0.0
1    1.0
dtype: float64

In [49]:
# pitfalls with chained indexing

In [50]:
data.loc[:, 'one'] = 1
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [51]:
data.iloc[2] = 5
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [52]:
data.loc[data['four'] > 5] = 3
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [53]:
data.loc[data.three == 5]['three'] = 6
data

C:\Users\vlad\AppData\Local\Temp\ipykernel_6704\2592037177.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  data.loc[data.three == 5]['three'] = 6

          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [54]:
data.loc[data.three == 5, 'three'] = 6
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3