In [1]:
# numpy ufuncs also work
# with pandas objects

In [2]:
import numpy as np
import pandas as pd

In [3]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

               b         d         e
Utah    1.175799  0.235050  0.509710
Ohio    0.862881  0.590167 -0.652983
Texas  -0.409508  1.756195 -2.034533
Oregon  1.383486  1.742398  0.467976

In [4]:
np.abs(frame)

               b         d         e
Utah    1.175799  0.235050  0.509710
Ohio    0.862881  0.590167  0.652983
Texas   0.409508  1.756195  2.034533
Oregon  1.383486  1.742398  0.467976

In [5]:
# .apply() method
# apply function on 1-d array

In [6]:
def f1(x):
    return x.max() - x.min()

In [7]:
frame.apply(f1)

b    1.792994
d    1.521146
e    2.544243
dtype: float64

In [8]:
frame.apply(f1, axis='columns')

Utah      0.940750
Ohio      1.515863
Texas     3.790728
Oregon    1.274422
dtype: float64

In [9]:
def f2(x):
    return pd.Series([x.min(), x.max()],
                     index=['min', 'max'])

In [10]:
frame.apply(f2)

            b         d         e
min -0.409508  0.235050 -2.034533
max  1.383486  1.756195  0.509710

In [11]:
def my_format(x):
    return f'{x:.2f}'

In [12]:
# .map() method
# apply function on 1 scalar

In [13]:
frame.map(my_format)

            b     d      e
Utah     1.18  0.24   0.51
Ohio     0.86  0.59  -0.65
Texas   -0.41  1.76  -2.03
Oregon   1.38  1.74   0.47

In [14]:
frame['e'].map(my_format)

Utah       0.51
Ohio      -0.65
Texas     -2.03
Oregon     0.47
Name: e, dtype: str