In [ ]:
# sorting

# .sort_index() method

In [2]:
import numpy as np
import pandas as pd

In [3]:
obj = pd.Series(np.arange(4),
                index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [4]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [5]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [7]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [9]:
frame.sort_index(axis='columns')

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [10]:
frame.sort_index(axis='columns', ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [13]:
# .sort_values() method

In [14]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [15]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [16]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [17]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [18]:
obj.sort_values(na_position='first')

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [19]:
frame = pd.DataFrame({'b': [4, 7, -3, 2],
                      'a': [0, 1, 0, 1]})
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [20]:
frame.sort_values('b')

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [21]:
frame.sort_values(['a', 'b'])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [22]:
frame.sort_values(['b', 'a'])

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [23]:
# ranking

# .rank() method

In [24]:
obj = pd.Series([7, -5, 7, 4, 2, 0 ,4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [ ]:
obj.rank()

# method='average' (default)
#
# element 4: index 4 and index 5
#       (4 + 5) / 2 = 4.5
# element 7: index 6 and index 7
#       (6 + 7) / 2 = 6.5

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [26]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [27]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [28]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2],
                      'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [29]:
frame.rank(axis='columns')

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0