In [1]:
# not unique labels

In [2]:
import numpy as np
import pandas as pd

In [3]:
obj = pd.Series(np.arange(5), 
                index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [4]:
obj.index.is_unique

False

In [5]:
obj.loc['a']

a    0
a    1
dtype: int64

In [6]:
obj.loc['c']

np.int64(4)

In [7]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),
                  index=['a', 'a', 'b', 'b', 'c'])
df

          0         1         2
a -2.209433 -1.514066 -0.240499
a -0.111716 -1.803200  1.237734
b -0.222089 -0.225699  1.188992
b -1.972606 -0.963238  0.934146
c  0.565799  1.154947 -1.316429

In [8]:
df.loc['b']

          0         1         2
b -0.222089 -0.225699  1.188992
b -1.972606 -0.963238  0.934146

In [9]:
df.loc['c']

0    0.565799
1    1.154947
2   -1.316429
Name: c, dtype: float64